# Generated by Django 4.2.5 on 2023-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria')),
                ('introduccion', models.TextField(blank=True, max_length=1500, null=True, verbose_name='introducción')),
                ('seccion1', models.TextField(blank=True, max_length=3500, null=True, verbose_name='seccion1')),
                ('seccion2', models.TextField(blank=True, max_length=3500, null=True, verbose_name='seccion2')),
                ('seccion3', models.TextField(blank=True, max_length=3500, null=True, verbose_name='seccion3')),
                ('seccion4', models.TextField(blank=True, max_length=3500, null=True, verbose_name='seccion4')),
                ('seccion5', models.TextField(blank=True, max_length=3500, null=True, verbose_name='seccion5')),
                ('seccion6', models.TextField(blank=True, max_length=3500, null=True, verbose_name='seccion6')),
                ('seccion7', models.TextField(blank=True, max_length=3500, null=True, verbose_name='seccion7')),
                ('seccion8', models.TextField(blank=True, max_length=3500, null=True, verbose_name='seccion8')),
                ('by', models.CharField(blank=True, max_length=500, null=True, verbose_name='Escrito por')),
                ('appointment1', models.TextField(blank=True, max_length=600, null=True, verbose_name='Cita1')),
                ('name_appointment1', models.TextField(blank=True, max_length=600, null=True, verbose_name='Nombre de la cita1')),
                ('appointment2', models.TextField(blank=True, max_length=600, null=True, verbose_name='Cita2')),
                ('name_appointment2', models.TextField(blank=True, max_length=600, null=True, verbose_name='Nombre de la cita2')),
                ('appointment3', models.TextField(blank=True, max_length=600, null=True, verbose_name='Cita3')),
                ('name_appointment3', models.TextField(blank=True, max_length=600, null=True, verbose_name='Nombre de la cita3')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
