# Generated by Django 4.2.5 on 2023-10-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='appointment1',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='appointment2',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='appointment3',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='name_appointment1',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='name_appointment2',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='name_appointment3',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='seccion2',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='seccion3',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='seccion4',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='seccion5',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='seccion6',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='seccion7',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='seccion8',
        ),
        migrations.AlterField(
            model_name='investigation',
            name='seccion1',
            field=models.TextField(blank=True, max_length=10500, null=True, verbose_name='seccion1'),
        ),
    ]
