# Generated by Django 4.2.5 on 2023-10-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0003_etiqueta_investigation_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
