# Generated by Django 4.2.5 on 2023-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image2',
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
    ]
