# Generated by Django 4.2.5 on 2023-09-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_licencia', models.CharField(blank=True, max_length=500, null=True, verbose_name='Numero de la licencia')),
                ('development', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre del inmueble')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección del inmueble')),
                ('descripcion', models.CharField(blank=True, max_length=800, null=True, verbose_name='Descripción del inmueble')),
                ('characteristics', models.CharField(blank=True, max_length=800, null=True, verbose_name='Características del inmueble')),
                ('owner', models.CharField(blank=True, max_length=800, null=True, verbose_name='Propietario')),
                ('agreement_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de acuerdo')),
                ('surface', models.FloatField(blank=True, null=True, verbose_name='Superficie')),
                ('levels', models.IntegerField(blank=True, null=True, verbose_name='Niveles')),
                ('departments', models.IntegerField(blank=True, null=True, verbose_name='Departamentos')),
                ('local', models.IntegerField(blank=True, null=True, verbose_name='Locales')),
                ('offices', models.IntegerField(blank=True, null=True, verbose_name='Oficinas')),
                ('parking', models.IntegerField(blank=True, null=True, verbose_name='Estacionamiento')),
                ('required_parking', models.IntegerField(blank=True, null=True, verbose_name='Estacionamientos requeridos')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='precio')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image11', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image12', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image13', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image14', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image15', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image16', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image17', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image18', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image19', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('image20', models.ImageField(blank=True, null=True, upload_to='galery/%Y-%m-%d/', verbose_name='galeria')),
                ('credits_image', models.CharField(blank=True, max_length=300, null=True, verbose_name='Creditos de las imagenes')),
                ('link_image', models.URLField(blank=True, null=True, verbose_name='Link de los creditos')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
