# Generated by Django 4.2.5 on 2023-10-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf', verbose_name='pdf'),
        ),
    ]
