# Generated by Django 4.2.5 on 2023-11-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0002_inmueble_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image14',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image15',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image16',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image17',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image18',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image19',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image20',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='image9',
        ),
    ]
