# Generated by Django 4.2.5 on 2024-01-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0003_remove_inmueble_image1_remove_inmueble_image10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección del inmueble'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='streat',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Colonia'),
        ),
    ]
