# Generated by Django 4.2.5 on 2024-01-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0004_inmueble_number_inmueble_streat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='numero'),
        ),
    ]
