# Generated by Django 4.2.5 on 2024-01-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0005_alter_inmueble_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='alert',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Alerta de factibilidad'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
