# Generated by Django 4.2.5 on 2023-09-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='test', max_length=400, verbose_name='Calle')),
                ('colony', models.CharField(default='test', max_length=600, verbose_name='Colonia')),
                ('municipality', models.CharField(max_length=300, verbose_name='Municipio')),
                ('since', models.CharField(default='test', max_length=400, verbose_name='Desde')),
                ('latitude_since', models.FloatField(null=True, verbose_name='Desde latitude')),
                ('longitude_since', models.FloatField(null=True, verbose_name='Desde longitud')),
                ('until', models.CharField(default='test', max_length=400, verbose_name='Hasta')),
                ('latitude_until', models.FloatField(null=True, verbose_name='Hasta latitude')),
                ('longitude_until', models.FloatField(null=True, verbose_name='Hasta longitud')),
            ],
        ),
    ]
